#!/bin/bash -xe

control_c()
# run if user hits control-c
{
  echo -en "\n*** Ouch! Exiting ***\n"
  cleanup
  exit $?
}

trap control_c INT KILL

# capture an interrupt
trap 'echo "signal detected..."' 0 2 3 4 5 6 7 8 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62

echo "This is a test... Waiting for signals. C-c to stop."

# display something
while true; do read x; done

# exit shell script with 0 signal
exit 0
